//
//  MTISIMDTypeKVCSupport.h
//  MetalPetalJS
//
//  Created by Yu Ao on 2018/6/25.
//
//  Auto generated by generate-simd-kvc-support.sh

#import <Foundation/Foundation.h>
#import <MetalPetal/MetalPetal.h>
#import <JavascriptCore/JavascriptCore.h>

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, MTISIMDType) {
    MTISIMDTypeFloat2,
    MTISIMDTypeFloat3,
    MTISIMDTypeFloat4,
    MTISIMDTypeDouble2,
    MTISIMDTypeDouble3,
    MTISIMDTypeDouble4,
    MTISIMDTypeInt2,
    MTISIMDTypeInt3,
    MTISIMDTypeInt4,
    MTISIMDTypeUInt2,
    MTISIMDTypeUInt3,
    MTISIMDTypeUInt4,
    MTISIMDTypeFloat2x2,
    MTISIMDTypeFloat2x3,
    MTISIMDTypeFloat2x4,
    MTISIMDTypeFloat3x2,
    MTISIMDTypeFloat3x3,
    MTISIMDTypeFloat3x4,
    MTISIMDTypeFloat4x2,
    MTISIMDTypeFloat4x3,
    MTISIMDTypeFloat4x4,
    MTISIMDTypeDouble2x2,
    MTISIMDTypeDouble2x3,
    MTISIMDTypeDouble2x4,
    MTISIMDTypeDouble3x2,
    MTISIMDTypeDouble3x3,
    MTISIMDTypeDouble3x4,
    MTISIMDTypeDouble4x2,
    MTISIMDTypeDouble4x3,
    MTISIMDTypeDouble4x4,
    MTISIMDTypeInt2x2,
    MTISIMDTypeInt2x3,
    MTISIMDTypeInt2x4,
    MTISIMDTypeInt3x2,
    MTISIMDTypeInt3x3,
    MTISIMDTypeInt3x4,
    MTISIMDTypeInt4x2,
    MTISIMDTypeInt4x3,
    MTISIMDTypeInt4x4,
    MTISIMDTypeUInt2x2,
    MTISIMDTypeUInt2x3,
    MTISIMDTypeUInt2x4,
    MTISIMDTypeUInt3x2,
    MTISIMDTypeUInt3x3,
    MTISIMDTypeUInt3x4,
    MTISIMDTypeUInt4x2,
    MTISIMDTypeUInt4x3,
    MTISIMDTypeUInt4x4
};

FOUNDATION_EXPORT void MTISIMDTypeExportToJSContext(JSContext *context);

FOUNDATION_EXPORT void MTISetSIMDValueForKey(id object, NSString *key, MTIVector *value, MTISIMDType type);

FOUNDATION_EXPORT MTIVector * MTIGetSIMDValueForKey(id object, NSString *key, MTISIMDType type);

NS_ASSUME_NONNULL_END